name: cache test
on:
  push:
    branches:
      - main

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: golang/hello
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: golang/hello/go.mod
          cache: false

      - uses: actions/cache@v4
        id: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-hello-${{ hashFiles('golang/hello/go.sum') }}
          restore-keys: |
            go-hello-

      - run: go build
      - run: ./hello